stages:
  - test

test:unit-test:
  tags:
    - android
    - unit-test
  stage: test
  script: "scripts/unit-test.sh"
  artifacts:
    name: "Unit-$CI_COMMIT_SHA-$CI_COMMIT_REF_NAME"
    paths:
      - app/build/reports/tests
      - app/build/reports/jacoco
    expire_in: 1 week

test:static-analysis:
  tags:
    - android
  stage: test
  script: "scripts/static-analysis.sh"
  artifacts:
    name: "StaticAnalysis-$CI_COMMIT_SHA-$CI_COMMIT_REF_NAME"
    paths:
      - app/build/reports/detekt
    expire_in: 1 week