before_script:
- "chmod +x ./gradlew"
- "chmod +x scripts/unit-test.sh"
- "chmod +x scripts/static-analysis.sh"

stages: [ "Tests" ]

"Unit Tests":
  tags: [ "android", "unit-test" ]
  stage: "Tests"
  script: "scripts/unit-test.sh"
  artifacts:
    name: "Unit-$CI_COMMIT_SHA-$CI_COMMIT_REF_NAME"
    paths:
      - app/build/reports/tests
      - app/build/reports/jacoco
    expire_in: 1 week

"Static Analysis Tests":
  tags: [ "android" ]
  stage: "Tests"
  script: "scripts/static-analysis.sh"
  artifacts:
    name: "StaticAnalysis-$CI_COMMIT_SHA-$CI_COMMIT_REF_NAME"
    paths:
      - app/build/reports/staticAnalysisTests
    expire_in: 1 week