before_script:
- "chmod +x ./gradlew"
- "chmod +x scripts/unit-test.sh"

stages: [ "Tests" ]

"Unit Tests":
  tags: [ "android", "unit-test" ]
  stage: "Tests"
  script: "scripts/unit-test.sh"
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - app/build/reports/tests
    expire_in: 1 week