name: Slash Commands
on:
  issue_comment:
    types: [created]
jobs:
  slash-command:
    if: contains(github.event.comment.body, '/ci')
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Analysis detekt
        run: |
          echo "${{ toJSON(github) }}"
