name: Slash Commands
on:
  issue_comment:
    types: [created]
jobs:
  slash-command:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Analysis detekt
        run: |
          echo "${{ fromJSON(github) }}"
