# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: 
  push:
    branches:
      - develop

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout private tools
        uses: actions/checkout@v2
        with:
          repository: scoremedia/github-actions-playground
          token: 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
          path: my-tools
      - name: Sample
        run: |
          ls my-tools
      
#       - name: Generate token
#         id: generate_token
#         uses: tibdex/github-app-token@v1
#         with:
#           app_id: ${{ secrets.APP_ID }}
#           private_key: ${{ secrets.APP_SECRET }}
#           # Optional (defaults to the current repository).
#           # repository: owner/repo
#       - name: Use token
#         env:
#           TOKEN: ${{ steps.generate_token.outputs.token }}
#         run: |
#           echo "The generated token is masked: ${TOKEN}"
