# This is a basic workflow to help you get started with Actions


name: CI

# Controls when the action will run. 
on: 
  push:
    branches:
      - sample-dev

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_SECRET }}
          # Optional (defaults to the current repository).
          # repository: owner/repo
      - name: Use token
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR=$(gh pr view sample-dev --json state,number)
          PR_STATE=$(echo ${PR} | jq .state)
          PR_NUMBER=$(echo ${PR} | jq .number)
          echo "${PR_STATE}"
          echo "${PR_NUMBER}"
