# This is a basic workflow to help you get started with Actions


name: CI

# Controls when the action will run. 
on: 
  push:
    branches:
      - sample-dev

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_SECRET }}
          # Optional (defaults to the current repository).
          # repository: owner/repo
      - name: Use token
        env:
          TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          echo "The generated token is masked: ${TOKEN}"
      - name: Create PR internal to dev
        uses: scorebet/pull-request@v2
        with:
          source_branch: sample-dev
          destination_branch: develop
          pr_title: "Changes on INTERNAL merging into DEV"
          pr_body: "<p align='center'><img src='https://i.imgur.com/FoTJB8S.png'/><br/><b>PLEASE DON'T SQUASH MERGE</b></p>"
          pr_label: "needs-review,eod,auto-generated"
          github_token: ${{ steps.generate_token.outputs.token }}
